#!/usr/bin/env python3
"""Generate fixed-point constants; only this host tool uses floating point."""
import math
from pathlib import Path
p=Path(__file__).resolve().parents[1]/'overlay/apps/gui/spectrum/tables.h'
tables=[('int16_t','spectrum_cos',[round(32767*math.cos(2*math.pi*i/1024)) for i in range(512)]),('int16_t','spectrum_sin',[round(-32767*math.sin(2*math.pi*i/1024)) for i in range(512)]),('int16_t','spectrum_hann',[round(32767*(0.5-0.5*math.cos(2*math.pi*i/1024))) for i in range(1024)]),('uint32_t','spectrum_exp2',[round(65536*2**(i/256)) for i in range(256)])]
s='/* Generated by tools/generate-tables.py. GPL-2.0-or-later. */\n'
for kind,name,values in tables:
    s+=f'static const {kind} {name}[{len(values)}] = {{\n'
    for start in range(0,len(values),12):s+='    '+', '.join(map(str,values[start:start+12]))+',\n'
    s+='};\n'
p.write_text(s)
